<?php
/*
* Template Name: Home (Front Page)
*/
get_header();?>
<!-- Font template -->
<div class="container">	
	<?php if(have_posts()): the_post(); ?>
	<div class="row">
		<div class="col-md-9 main-content-wrap">						<h1 class="main-intro-heading"><?php the_title(); ?></h1>			<?php the_content(); ?> 									<h2 class="programs-heading">Loan Programs</h2>			<?php 				$args = array( 'post_type' => 'loan_program' );								$the_query = new WP_Query( $args );				if ( $the_query->have_posts() ) { ?>											<?php while ( $the_query->have_posts() ) { $the_query->the_post(); ?>							<article class="programs-cont col-md-6">								<div class="program-icon">																	<i class="fa <?php echo get_post_meta($the_query-> post->ID, 'loan_program_icon_font_awesome_tag', true) ?>"></i>																</div>																<div class="program-content">																	<h4 class="program-title">																			<?php echo get_the_title(); ?> 																		</h4>																		<div class="program-text">																			<?php echo get_the_content(); ?> 																		</div>																</div>																					</article>													<?php }				} else {										echo 'Please add a few Loan Programs';									}								wp_reset_postdata();					?>			<div class="clear"></div>			<h2 class="services-heading">Our Services</h2>			<?php 				$args = array( 'post_type' => 'services' );								$the_query = new WP_Query( $args );				if ( $the_query->have_posts() ) { ?>											<?php while ( $the_query->have_posts() ) { $the_query->the_post(); ?>							<article class="programs-cont col-md-6">								<div class="program-icon">																	<i class="fa <?php echo get_post_meta($the_query-> post->ID, 'loan_program_icon_font_awesome_tag', true) ?>"></i>																</div>																<div class="program-content">																	<h4 class="program-title">																			<a href="<?php the_permalink(); ?>"><?php echo get_the_title(); ?></a> 																		</h4>																		<div class="program-text">																			<?php the_content('<p>Read More <i class="fa fa-chevron-circle-right"></i></p>'); ?> 																		</div>																</div>																					</article>													<?php }				} else {										echo 'Please add a few services';									}								wp_reset_postdata();					?>					
		</div>				<div class="col-md-3 right-sidebar">						<?php if ( is_active_sidebar( 'sidebar-widgets' ) ) : ?>				<div class="first front-widgets">					<?php dynamic_sidebar( 'sidebar-widgets' ); ?>				</div><!-- .first -->			<?php endif; ?>		  		</div>
	</div>
	<?php endif; ?>
</div><div class="carouse-bg">	<div class="container">		<div class="row col-md-12">		<!-- Carousel -->			<div id="owl-example" class="owl-carousel">			<?php 					$args = array( 'post_type' => 'client-carousel' );										$the_query = new WP_Query( $args );					if ( $the_query->have_posts() ) { ?>													<?php while ( $the_query->have_posts() ) { $the_query->the_post(); ?>							<div><?php echo get_the_post_thumbnail(); ?></div> <?php //remove one of the line; ?>							<div><?php echo get_the_post_thumbnail(); ?></div>																				<?php }					} else {												echo 'Please add a few clients logos!';											}										wp_reset_postdata();							?>			  			</div>		</div>	</div></div><div class="clear"></div><div class="footer-top">	<footer>		<div class="container">			<div class="row">				<div class="col-md-4 footer-top-widgets">					<?php if ( is_active_sidebar( 'sidebar-foot1' ) ) : ?>						<div class="first front-widgets">							<?php dynamic_sidebar( 'sidebar-foot1' ); ?>						</div><!-- .first -->					<?php endif; ?>				</div>				<div class="col-md-4 footer-top-widgets">					<?php if ( is_active_sidebar( 'sidebar-foot2' ) ) : ?>						<div class="first front-widgets">							<?php dynamic_sidebar( 'sidebar-foot2' ); ?>						</div><!-- .first -->					<?php endif; ?>				</div>				<div class="col-md-4 footer-top-widgets">					<?php if ( is_active_sidebar( 'sidebar-foot3' ) ) : ?>						<div class="first front-widgets">							<?php dynamic_sidebar( 'sidebar-foot3' ); ?>						</div><!-- .first -->					<?php endif; ?>				</div>				<?php /*				<div class="col-md-3 footer-top-widgets">					<?php if ( is_active_sidebar( 'sidebar-foot4' ) ) : ?>						<div class="first front-widgets">							<?php dynamic_sidebar( 'sidebar-foot4' ); ?>						</div><!-- .first -->					<?php endif; ?>				</div> */ ?>			</div>		</div>		</footer></div>	
<?php get_footer();?>